first_name= input("What is your first name? ")
last_name=input ("What is your last name? ")
country=input ("Hi "+ first_name +" where are you from? ")
age=input("Hi "+ first_name +" what is your age? ")
future=input ("Hi "+ first_name+"  what do you want to be in the future? ")
print ("Your details are given below")
print( "Your full name is "+first_name+" "+last_name + "....... concatenation applied")
print( f"Your full name is {first_name} {last_name} ...format string applied")
print( "Your full name is", first_name, last_name, "....separated by coma method applied")
print( "You are from "+country)
print( f"You are from {country} ....format string applied")
print( "You are "+age+ " years old")
print("Your want to be "+future+ " in the future")
input('press enter to exit')